using Nop.Core;

namespace EFiling.Nop.Domain;

/// <summary>
/// Per-document court status within a filing. Updated by NFRC callbacks.
/// One row per document submitted (lead + connected).
/// </summary>
public class EFilingDocumentRecord : BaseEntity
{
    /// <summary>FK to EFilingOrderRecord.Id.</summary>
    public int EFilingOrderRecordId { get; set; }

    /// <summary>Document reference ID from submission (e.g., "doc0", "doc1").</summary>
    public string DocumentReferenceId { get; set; } = string.Empty;

    /// <summary>Document type code from court policy (e.g., "218620").</summary>
    public string DocumentCode { get; set; } = string.Empty;

    /// <summary>Our FileControlId sent in submission.</summary>
    public string? FileControlId { get; set; }

    /// <summary>Whether this is the lead document.</summary>
    public bool IsLeadDocument { get; set; }

    /// <summary>
    /// Document-level filing status: ACCEPTED, REJECTED, RECEIVED_UNDER_REVIEW, RECEIVED.
    /// </summary>
    public string? DocumentFilingStatusCode { get; set; }

    /// <summary>
    /// Document status text: R (Received), F (Filed), I (Issued), RJ (Rejected),
    /// RP (Proposed-Received), FG (Filed and Granted), IF (Issued-Filed).
    /// </summary>
    public string? DocumentStatusText { get; set; }

    /// <summary>
    /// Document disposition type (NFRC #3): GRA, DEN, ORD, OAI.
    /// Null until judicial officer acts on proposed orders/stipulations.
    /// </summary>
    public string? DocumentDispositionType { get; set; }

    /// <summary>
    /// UTC timestamp at which the judicial officer rendered the disposition recorded in
    /// <see cref="DocumentDispositionType"/> (NFRC #3). Optional per WSDL
    /// <c>ReviewedDocumentTypeExt</c> at <c>FilingReviewMDEPort.wsdl:9315</c>
    /// (schema type <c>nc:DateType</c>). Null until the court emits an NFRC #3 with the
    /// element populated. All values are stored as UTC; the parser normalizes wire-format
    /// timestamps with TZ offsets to UTC before persistence (Q22-B fix — Phase 5.7).
    /// </summary>
    public DateTime? DocumentDispositionDate { get; set; }

    /// <summary>Rejection reason text (if document rejected).</summary>
    public string? RejectionReasonText { get; set; }

    /// <summary>URL to conformed copy (from NFRC, expires in 7 days).</summary>
    public string? ConformedCopyUrl { get; set; }

    /// <summary>Court-assigned document ID (from COURT_RECORD_MDE).</summary>
    public string? CourtDocumentId { get; set; }

    /// <summary>Original filename submitted.</summary>
    public string? OriginalFileName { get; set; }

    /// <summary>Original Azure Blob URL for the uploaded document.</summary>
    public string? BlobUrl { get; set; }

    /// <summary>Human-readable document type description (e.g., "Complaint", "Civil Case Cover Sheet").</summary>
    public string? DocumentDescription { get; set; }

    /// <summary>Whether this document was generated by the court (true) or uploaded by the filer (false).</summary>
    public bool IsCourtGenerated { get; set; }

    /// <summary>When this record was created (UTC).</summary>
    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>When this record was last updated (UTC).</summary>
    public DateTime UpdatedUtc { get; set; } = DateTime.UtcNow;
}
