using System.Xml.Linq;
using EFiling.Providers.JTI.Config;
using EFiling.Tests.SubsequentFilingRoundTrip;

namespace EFiling.Tests;

/// <summary>
/// T-3a S4 completeness tests. Asserts that the three v2 schema slice files
/// (<c>JtiClassTypeSchema.json</c>, <c>JtiTagSchema.json</c>,
/// <c>JtiCaseCategoryPolicy.json</c>) are loadable, contain their expected
/// WSDL / catalog-declared entries, and that the legacy back-compat API
/// continues to project correctly.
///
/// Retires the PowerShell scaffolding in <c>tools/validate-classtype-schema.ps1</c>
/// (per T-3a S4 plan).
/// </summary>
public class JtiFieldSchemaProviderTests
{
    // ───────────────────────────────────────────────────────────────────
    // Slice 1: ClassType schema — 19 WSDL classTypes
    // ───────────────────────────────────────────────────────────────────

    private static readonly string[] ExpectedClassTypes =
    {
        "caseParticipant", "caseAssignment", "contact", "codeList", "date", "boolean",
        "text", "crsReceiptNumber", "number", "currency", "email", "action", "attorney",
        "address", "document", "scheduledEvent", "caseSpecialStatus", "judgment", "relatedCase"
    };

    [Fact]
    public void ClassTypeSchema_ContainsAll19WsdlClassTypes()
    {
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();

        Assert.NotNull(schema);
        Assert.Equal(19, schema.ClassTypes.Count);

        foreach (var expected in ExpectedClassTypes)
        {
            Assert.True(schema.ClassTypes.ContainsKey(expected),
                $"ClassType '{expected}' is missing from JtiClassTypeSchema.json. All 19 WSDL DocumentFilingMetaDataItem fields must be present per T-3a bar.");
        }
    }

    [Fact]
    public void ClassTypeSchema_EvidenceLevelDistribution_MatchesCatalog()
    {
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();

        var counts = new Dictionary<string, int> { ["V0"] = 0, ["V1"] = 0, ["V2"] = 0, ["V3"] = 0 };
        foreach (var ct in schema.ClassTypes.Values)
        {
            Assert.NotNull(ct.Evidence);
            Assert.Contains(ct.Evidence.Level, counts.Keys);
            counts[ct.Evidence.Level]++;
        }

        // Catalog §3 evidence tally as of Step #46:
        //   V0 (Tier B live):    caseParticipant, caseAssignment                                  (2)
        //   V1 (Tier A backed):  contact, codeList, date, boolean                                 (4)
        //   V2 (Layer A only):   text, currency, attorney, judgment, crsReceiptNumber             (5)
        //   V3 (WSDL only):      number, email, action, address, document, scheduledEvent,
        //                        caseSpecialStatus, relatedCase                                   (8)
        //
        // Step #46 promoted crsReceiptNumber V3 → V2 based on Layer A evidence in the
        // JTI Document Metadata HTML doc Class Types section
        // ("String. The calendar reservation number generated by the CRS system.").
        // Source: `docs/fileing files/Document Metadata/Document Metadata _ EFM
        // Documentation.html` line 626. Same evidence tier as text/currency/attorney.
        Assert.Equal(2, counts["V0"]);
        Assert.Equal(4, counts["V1"]);
        Assert.Equal(5, counts["V2"]);
        Assert.Equal(8, counts["V3"]);
    }

    [Fact]
    public void ClassTypeSchema_EveryClassType_HasWsdlGroundingAndWireWrapper()
    {
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();

        foreach (var (name, ct) in schema.ClassTypes)
        {
            Assert.NotNull(ct.Wsdl);
            Assert.False(string.IsNullOrEmpty(ct.Wsdl.Field), $"classType '{name}' has no WSDL field name");
            Assert.False(string.IsNullOrEmpty(ct.Wsdl.ClrType), $"classType '{name}' has no CLR type");
            Assert.NotNull(ct.Wsdl.XsdOrder);

            Assert.NotNull(ct.Wire);
            Assert.False(string.IsNullOrEmpty(ct.Wire.WrapperElement), $"classType '{name}' has no wire wrapper element");
        }
    }

    [Fact]
    public void ClassTypeSchema_XsdOrder_MatchesWsdlRange()
    {
        // Per catalog §3.0: classType XmlElement Order values occupy 1..10 and 12..20.
        // Order=11 is idReferences (shared existing-data wrapper), NOT a classType.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var validOrders = Enumerable.Range(1, 10).Concat(Enumerable.Range(12, 9)).ToHashSet();

        var observedOrders = new HashSet<int>();
        foreach (var (name, ct) in schema.ClassTypes)
        {
            Assert.NotNull(ct.Wsdl?.XsdOrder);
            var order = ct.Wsdl.XsdOrder.Value;
            Assert.Contains(order, validOrders);
            Assert.True(observedOrders.Add(order), $"Duplicate xsdOrder {order} between '{name}' and another classType");
        }

        // All 19 valid order slots should be populated.
        Assert.Equal(19, observedOrders.Count);
    }

    // ───────────────────────────────────────────────────────────────────
    // Slice 2: Tag schema — 9 tags (4 evidence-backed + 5 hypothesis)
    // ───────────────────────────────────────────────────────────────────

    private static readonly string[] ExpectedTags =
    {
        "E_SERVICE", "FEE_EXEMPTION", "EFSP_FIRST_APPEARANCE_PAID", "EFSP_EMAIL",
        "EFSP_GOVERNMENT_EXEMPT", "EFSP_FEE_WAIVER_FILED", "SELF_REPRESENTED", "SEALED", "ERRONEOUSLY_SUED_TRUENAME"
    };

    [Fact]
    public void TagSchema_ContainsAll9KnownTags()
    {
        var schema = JtiFieldSchemaProvider.GetTagSchema();

        Assert.NotNull(schema);
        Assert.Equal(9, schema.Tags.Count);

        foreach (var expected in ExpectedTags)
        {
            Assert.True(schema.Tags.ContainsKey(expected),
                $"Tag '{expected}' is missing from JtiTagSchema.json. Expected 4 evidence-backed + 5 hypothesis = 9 total per catalog §4.");
        }
    }

    [Fact]
    public void TagSchema_FourTagsAreEvidenceBacked_FiveAreHypothesis()
    {
        var schema = JtiFieldSchemaProvider.GetTagSchema();

        var evidenceBacked = schema.Tags.Where(kv => !kv.Value.AwaitingEvidence).Select(kv => kv.Key).ToList();
        var hypothesis = schema.Tags.Where(kv => kv.Value.AwaitingEvidence).Select(kv => kv.Key).ToList();

        Assert.Equal(4, evidenceBacked.Count);
        Assert.Equal(5, hypothesis.Count);

        // The 4 evidence-backed tags per catalog §4.7.
        Assert.Contains("E_SERVICE", evidenceBacked);
        Assert.Contains("FEE_EXEMPTION", evidenceBacked);
        Assert.Contains("EFSP_FIRST_APPEARANCE_PAID", evidenceBacked);
        Assert.Contains("EFSP_EMAIL", evidenceBacked);
    }

    [Fact]
    public void TagSchema_FeeExemption_UsesDropdownWithEnumValues()
    {
        // Audit C-3 fix: FEE_EXEMPTION was type=checkbox in legacy schema; real wire is string-enum.
        var tag = JtiFieldSchemaProvider.GetTagV2("FEE_EXEMPTION");
        Assert.NotNull(tag);
        Assert.Equal("string-enum", tag.TagValueKind);
        Assert.Equal("dropdown", tag.UiType);
        Assert.NotNull(tag.EnumValues);
        Assert.Contains("GOVT_ENTITY", tag.EnumValues);
        Assert.Contains("FEE_WAIVER", tag.EnumValues);
    }

    [Fact]
    public void TagSchema_EServiceAndEfspEmail_ArePaired()
    {
        // Per catalog §4.1 + §4.4: EFSP_EMAIL is always a sibling of E_SERVICE=1.
        var eService = JtiFieldSchemaProvider.GetTagV2("E_SERVICE");
        var efspEmail = JtiFieldSchemaProvider.GetTagV2("EFSP_EMAIL");

        Assert.NotNull(eService);
        Assert.NotNull(efspEmail);

        Assert.Equal("EFSP_EMAIL", eService.PairedWith?.TagType);
        Assert.Equal("E_SERVICE", efspEmail.PairedWith?.TagType);
    }

    // ───────────────────────────────────────────────────────────────────
    // Schema ⇄ baseline cross-reference
    //
    // Partner to TierA_CoverageMatrixTests.Subsequent_TagTypeCounts_MatchCatalog_*,
    // which locks counts against the catalog. That test alone lets a drift slip where
    // a new baseline tag is added to ExpectedTagCounts + catalog but the schema file
    // is forgotten — the mapper's DetermineTagValue would then silently emit "1"
    // (see anchor in MetadataValueMapperTests). This cross-reference asserts every
    // tagType present in any canonical subsequent baseline is ALSO declared in
    // JtiTagSchema.json, so schema drift is caught at the schema layer too.
    //
    // The companion test `Initiation_Baselines_UseTypedExtensions_NotTagTypePattern`
    // locks the architectural finding from 2026-04-25 P0 preflight: initial filings
    // use TYPED `CaseAugmentationExt` children for case-level metadata, while
    // subsequent filings use the GENERIC tag-triple pattern. JtiTagSchema.json is
    // therefore subsequent-filing-specific by design — the initial-filing wire path
    // exercises a different code path through the builder (typed-element emission).
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void TagSchema_DeclaresEveryTagType_ObservedInSubsequentBaselines()
    {
        // Walk every subsequent baseline and collect the distinct tagType values that appear
        // on the wire. Assert each is a declared entry in JtiTagSchema.json.
        var schema = JtiFieldSchemaProvider.GetTagSchema();
        Assert.NotNull(schema);

        var observedTags = new HashSet<string>(StringComparer.Ordinal);
        foreach (var scenario in CanonicalScenarios.ByFilingType(FilingType.Subsequent))
        {
            var doc = SampleLoader.LoadXDocument(scenario);
            foreach (var tagEl in doc.Descendants().Where(e => e.Name.LocalName == "tagType"))
            {
                var value = tagEl.Value?.Trim();
                if (!string.IsNullOrEmpty(value))
                    observedTags.Add(value!);
            }
        }

        // Sanity: we expect to observe at least the 4 evidence-backed tags per §4.7.
        Assert.True(observedTags.Count >= 4,
            $"Baseline walk produced only {observedTags.Count} distinct tagTypes — expected ≥ 4 " +
            $"(E_SERVICE, FEE_EXEMPTION, EFSP_FIRST_APPEARANCE_PAID, EFSP_EMAIL). The sample loader " +
            $"or canonical registry may be broken.");

        // The actual cross-reference assertion.
        var missing = observedTags.Where(t => !schema.Tags.ContainsKey(t)).ToList();
        Assert.True(missing.Count == 0,
            "Schema drift detected: the following tagType values appear in baseline samples but " +
            "are NOT declared in JtiTagSchema.json. Add a schema entry (with tagValueKind + " +
            "evidence metadata) so the mapper and builder have an authoritative source:\n  - " +
            string.Join("\n  - ", missing));
    }

    [Fact]
    public void Initiation_Baselines_UseTypedExtensions_NotTagTypePattern()
    {
        // Architectural contract (discovered 2026-04-25 P0 preflight, locked here as
        // regression bar): the metadata-bearing wire structures differ by filing-type.
        //
        //   Subsequent filings (per-doc metadata):
        //     <DocumentFilingMetaData>
        //       <tagType>FEE_EXEMPTION</tagType>
        //       <tagValue>FEE_WAIVER</tagValue>
        //     </DocumentFilingMetaData>
        //
        //   Initial filings (case-level metadata):
        //     <CaseAugmentationExt>
        //       <p:efmFeeExemptionRequestType>...</p:efmFeeExemptionRequestType>
        //     </CaseAugmentationExt>
        //
        // This is why JtiTagSchema.json is correctly subsequent-filing-specific. The
        // initial-filing path emits typed `CaseAugmentationExt`/`PartyAugmentation` children
        // through a different builder code path. Auditing CC's metadata correctness (P2b)
        // therefore requires a different lens than auditing SF's (P2a).
        //
        // If a future initial-filing baseline starts using <tagType> elements, this test
        // catches it — that would represent a JTI wire-format change requiring schema +
        // builder + mapper updates.
        var initiationTagTypeCount = 0;
        foreach (var scenario in CanonicalScenarios.ByFilingType(FilingType.Initiation))
        {
            var doc = SampleLoader.LoadXDocument(scenario);
            initiationTagTypeCount += doc.Descendants()
                .Count(e => e.Name.LocalName == "tagType");
        }

        Assert.Equal(0, initiationTagTypeCount);
    }

    // ───────────────────────────────────────────────────────────────────
    // Slice 3: Case-category policy — 8 CA categories
    // ───────────────────────────────────────────────────────────────────

    private static readonly string[] ExpectedCategories =
    {
        "CIV", "UD", "FAM", "PRB", "MEN", "JUV", "CRI", "APP"
    };

    [Fact]
    public void CaseCategoryPolicy_Contains8CaCategories()
    {
        var schema = JtiFieldSchemaProvider.GetCaseCategoryPolicy();

        Assert.NotNull(schema);
        Assert.Equal(8, schema.Policies.Count);

        foreach (var expected in ExpectedCategories)
        {
            Assert.True(schema.Policies.ContainsKey(expected),
                $"Category '{expected}' is missing from JtiCaseCategoryPolicy.json.");
        }
    }

    [Fact]
    public void CaseCategoryPolicy_UdCategory_RequiresDisclaimer()
    {
        var ud = JtiFieldSchemaProvider.GetCaseCategoryPolicy("UD");
        Assert.NotNull(ud);
        Assert.Equal("UD", ud.CategoryCode);
        Assert.True(ud.RequiresUdDisclaimer);
    }

    [Fact]
    public void CaseCategoryPolicy_MentalHealth_RequiresDobForAsToParty()
    {
        var men = JtiFieldSchemaProvider.GetCaseCategoryPolicy("MEN");
        Assert.NotNull(men);
        Assert.True(men.RequiresDobForAsToParty);
    }

    // ───────────────────────────────────────────────────────────────────
    // Step #42 — T-7 + T-1.D wiring. KnownCategoryCodes maps
    // numeric per-court CASE_CATEGORY codelist codes (e.g., Madera "407200")
    // to JCCC 3-letter policy entries. The new
    // FindPolicyByCourtCategoryCode resolver bridges this for SF.cshtml UX
    // hooks (UD CCP §1161.2 disclaimer, Family minor-child redaction).
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void Step42_KnownCategoryCodes_UdEntry_ContainsMaderaUdCode()
    {
        var ud = JtiFieldSchemaProvider.GetCaseCategoryPolicy("UD");
        Assert.NotNull(ud);
        Assert.NotNull(ud.KnownCategoryCodes);
        Assert.Contains("407200", ud.KnownCategoryCodes);
    }

    [Fact]
    public void Step42_KnownCategoryCodes_FamEntry_ContainsMaderaFamilyCodes()
    {
        var fam = JtiFieldSchemaProvider.GetCaseCategoryPolicy("FAM");
        Assert.NotNull(fam);
        Assert.NotNull(fam.KnownCategoryCodes);
        // Madera Family Law / Family Dissolution codes per CIV-INI / FAM-INI catalog.
        Assert.Contains("211110", fam.KnownCategoryCodes);
        Assert.Contains("211120", fam.KnownCategoryCodes);
    }

    [Fact]
    public void Step42_KnownCategoryCodes_CivEntry_ContainsMaderaCivilCodes()
    {
        var civ = JtiFieldSchemaProvider.GetCaseCategoryPolicy("CIV");
        Assert.NotNull(civ);
        Assert.NotNull(civ.KnownCategoryCodes);
        // Madera Civil categories per CIV-INI catalog (411900 generic Civil,
        // 412910 No-Fee, 415110 Gov-Entity Exempt).
        Assert.Contains("411900", civ.KnownCategoryCodes);
        Assert.Contains("412910", civ.KnownCategoryCodes);
        Assert.Contains("415110", civ.KnownCategoryCodes);
    }

    [Fact]
    public void Step42_FindPolicyByCourtCategoryCode_ResolvesMaderaUd_ReturnsUdPolicy()
    {
        // Step #54: courtId-aware resolver. Madera-scoped lookup of
        // numeric code 407200 → UD policy via JtiCourtCategoryMappings.json.
        var policy = JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", "407200");
        Assert.NotNull(policy);
        Assert.Equal("UD", policy.CategoryCode);
        Assert.True(policy.RequiresUdDisclaimer);
    }

    [Fact]
    public void Step42_FindPolicyByCourtCategoryCode_ResolvesMaderaFamily_ReturnsFamPolicy()
    {
        // Step #42-R: assertion on `RequiresMinorChildRedaction`
        // was removed — that flag had zero JTI source and was deleted from the
        // model + policy JSON. The resolver-mapping assertion (Madera Family
        // code 211110 → FAM policy) remains valid and source-grounded.
        // Step #54: courtId-aware resolver.
        var policy = JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", "211110");
        Assert.NotNull(policy);
        Assert.Equal("FAM", policy.CategoryCode);
    }

    [Fact]
    public void Step42_FindPolicyByCourtCategoryCode_ResolvesMaderaCivilLimited_ReturnsCivPolicy()
    {
        // Civil 411900 should resolve to CIV — and CIV does NOT require the UD disclaimer
        // (the disclaimer is only attached to the UD sub-category, not the parent CIV).
        // Step #54: courtId-aware resolver.
        var policy = JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", "411900");
        Assert.NotNull(policy);
        Assert.Equal("CIV", policy.CategoryCode);
        Assert.NotEqual(true, policy.RequiresUdDisclaimer);
    }

    [Fact]
    public void Step42_FindPolicyByCourtCategoryCode_UnknownCode_ReturnsNull()
    {
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", "999999"));
    }

    [Fact]
    public void Step42_FindPolicyByCourtCategoryCode_EmptyInput_ReturnsNull()
    {
        // Step #54: courtId-aware resolver returns null on either
        // empty courtId OR empty code.
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", string.Empty));
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("madera", null!));
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode(string.Empty, "407200"));
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode(null!, "407200"));
    }

    [Fact]
    public void Step54_FindPolicyByCourtCategoryCode_UnknownCourt_ReturnsNull()
    {
        // Step #54: new courtId-aware behavior. An unknown court
        // (no entry in JtiCourtCategoryMappings.json) returns null even when
        // the code would have matched a different court's mapping.
        Assert.Null(JtiFieldSchemaProvider.FindPolicyByCourtCategoryCode("unknowncourt", "407200"));
    }

    [Fact]
    public void Step42_KnownCategoryCodes_NoOverlapBetweenPolicies()
    {
        // Each numeric per-court code should map to AT MOST ONE JCCC policy entry.
        // Overlap would indicate a data error — the resolver returns the first match
        // and downstream consumers would see ambiguous behavior.
        var schema = JtiFieldSchemaProvider.GetCaseCategoryPolicy();
        var codeToCategory = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var (catKey, policy) in schema.Policies)
        {
            if (policy.KnownCategoryCodes is not { Count: > 0 } codes)
                continue;

            foreach (var code in codes)
            {
                Assert.False(codeToCategory.ContainsKey(code),
                    $"Numeric category code '{code}' appears in BOTH '{codeToCategory.GetValueOrDefault(code)}' and '{catKey}'. " +
                    $"Each numeric code must map to exactly one JCCC policy.");
                codeToCategory[code] = catKey;
            }
        }
    }

    // ───────────────────────────────────────────────────────────────────
    // Legacy back-compat — pre-T-3a callers must continue to work
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void Legacy_GetSchema_ReturnsProjectedClassTypesAndTags()
    {
        var schema = JtiFieldSchemaProvider.GetSchema();

        Assert.NotNull(schema);
        // Legacy projection should contain ALL v2 classTypes + tags now, not just the pre-T-3a 8/5.
        Assert.Equal(19, schema.ClassTypes.Count);
        Assert.Equal(9, schema.AdditionalInfoTags.Count);
    }

    [Fact]
    public void Legacy_GetClassType_KnownValue_ReturnsDefinition_CaseInsensitive()
    {
        var def = JtiFieldSchemaProvider.GetClassType("caseParticipant");
        Assert.NotNull(def);
        Assert.NotEmpty(def.Variants);

        // Case-insensitive lookup per legacy contract.
        var lower = JtiFieldSchemaProvider.GetClassType("CASEPARTICIPANT");
        Assert.NotNull(lower);
    }

    [Fact]
    public void Legacy_GetClassType_Unknown_ReturnsNull()
    {
        var def = JtiFieldSchemaProvider.GetClassType("definitelyNotARealClassType");
        Assert.Null(def);
    }

    [Fact]
    public void Legacy_GetClassType_NullOrEmpty_ReturnsNull()
    {
        Assert.Null(JtiFieldSchemaProvider.GetClassType(""));
        Assert.Null(JtiFieldSchemaProvider.GetClassType(null!));
    }

    [Fact]
    public void Legacy_GetAdditionalInfoTag_KnownTag_ReturnsDefinition_CaseInsensitive()
    {
        var def = JtiFieldSchemaProvider.GetAdditionalInfoTag("E_SERVICE");
        Assert.NotNull(def);
        Assert.False(string.IsNullOrEmpty(def.Label));

        var lower = JtiFieldSchemaProvider.GetAdditionalInfoTag("e_service");
        Assert.NotNull(lower);
    }

    [Fact]
    public void Legacy_GetAdditionalInfoTag_Unknown_ReturnsNull()
    {
        Assert.Null(JtiFieldSchemaProvider.GetAdditionalInfoTag("TOTALLY_FAKE_TAG"));
    }

    // ───────────────────────────────────────────────────────────────────
    // v2 accessors — rich data availability
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void V2_CaseParticipant_HasEvidenceV0AndWsdlGrounding()
    {
        var cp = JtiFieldSchemaProvider.GetClassTypeV2("caseParticipant");
        Assert.NotNull(cp);
        Assert.Equal("V0", cp.Evidence?.Level);
        Assert.Equal("caseParticipantValue", cp.Wsdl?.Field);
        Assert.Equal(9, cp.Wsdl?.XsdOrder);
        Assert.True(cp.Variants.ContainsKey("person"));
        Assert.True(cp.Variants.ContainsKey("organization"));
    }

    [Fact]
    public void V2_Attorney_Has_V2_WithKnownBug()
    {
        var a = JtiFieldSchemaProvider.GetClassTypeV2("attorney");
        Assert.NotNull(a);
        Assert.Equal("V2", a.Evidence?.Level);
        Assert.True(a.AwaitingEvidence);
        Assert.NotNull(a.KnownBugs);
        Assert.NotEmpty(a.KnownBugs);
    }

    [Fact]
    public void V2_Judgment_UsesPluralWireElement()
    {
        // Per catalog §3.19: WSDL field name is PLURAL "judgments", not "judgmentValue".
        var j = JtiFieldSchemaProvider.GetClassTypeV2("judgment");
        Assert.NotNull(j);
        Assert.Equal("judgments", j.Wsdl?.Field);
        Assert.Equal("judgments", j.Wire?.WrapperElement);
    }

    [Fact]
    public void V2_IdReferencesOrder_IsNotAClassType()
    {
        // Per WSDL: DocumentFilingMetaDataItem Order=11 is idReferences — a shared
        // existing-data wrapper, NOT a classType. Our schema must NOT claim Order=11
        // for any classType.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        foreach (var (name, ct) in schema.ClassTypes)
        {
            Assert.NotEqual(11, ct.Wsdl?.XsdOrder);
        }
    }

    // ───────────────────────────────────────────────────────────────────
    // T-4-A pre-implementation additions: renderHint /
    // variantSelector / notSurfacedWsdlFields must survive JSON deserialization
    // so the client-side schemaLoader can consume them. Without these tests,
    // a future POCO refactor could silently drop the fields and the renderer
    // would fall back to "infer layout from fields.length" — the exact
    // anti-pattern T-4-A.1 rule 7 forbids.
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void TFourA_AllClassTypes_DeclareRenderHint()
    {
        // T-4-A.1 rule 7: renderHint dispatches composite/scalar/dropdown/deferred.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var allowedHints = new HashSet<string> { "compositeCard", "scalar", "dropdown", "complexDeferred" };

        foreach (var (name, ct) in schema.ClassTypes)
        {
            Assert.False(string.IsNullOrEmpty(ct.RenderHint),
                $"classType '{name}' is missing renderHint (required for T-4 renderer dispatch).");
            Assert.True(allowedHints.Contains(ct.RenderHint!),
                $"classType '{name}' has renderHint='{ct.RenderHint}' which is not in {{compositeCard,scalar,dropdown,complexDeferred}}.");
        }
    }

    [Fact]
    public void TFourA_CaseParticipant_HasVariantSelector_WithRadioPicker()
    {
        // T-4-A.1 rule 3: multi-variant classTypes MUST declare variantSelector.
        // caseParticipant is the only V0 multi-variant entry (person + organization).
        var cp = JtiFieldSchemaProvider.GetClassTypeV2("caseParticipant");
        Assert.NotNull(cp);
        Assert.NotNull(cp.VariantSelector);
        Assert.Equal("radio", cp.VariantSelector!.Type);
        Assert.Contains("person", cp.VariantSelector.Values);
        Assert.Contains("organization", cp.VariantSelector.Values);
        Assert.Equal("person", cp.VariantSelector.Default);
        Assert.False(string.IsNullOrEmpty(cp.VariantSelector.UxLabel),
            "variantSelector.uxLabel is required for filer-facing rendering.");
    }

    [Fact]
    public void TFourA_SingleVariantClassTypes_DoNotDeclareVariantSelector()
    {
        // T-4-A.1 rule 3 corollary: single-variant entries should NOT have variantSelector
        // (it would be misleading dead schema). Verifies only multi-variant entries opt in.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        foreach (var (name, ct) in schema.ClassTypes)
        {
            if (ct.Variants.Count <= 1)
            {
                Assert.Null(ct.VariantSelector);
            }
        }
    }

    [Fact]
    public void TFourA_CaseParticipantPerson_DocumentsFourNotSurfacedNiemFields()
    {
        // Audit § 5.2 + 2.2: schema deliberately surfaces 4 of 8 NIEM PersonNameType
        // fields. The 4 dropped fields are documented with concrete reasons.
        var cp = JtiFieldSchemaProvider.GetClassTypeV2("caseParticipant");
        Assert.NotNull(cp);
        var person = cp.Variants["person"];
        Assert.NotNull(person.NotSurfacedWsdlFields);
        Assert.Equal(4, person.NotSurfacedWsdlFields!.Count);

        var paths = person.NotSurfacedWsdlFields.Select(f => f.Path).ToList();
        Assert.Contains("nc:EntityPerson/nc:PersonName/nc:PersonNamePrefixText", paths);
        Assert.Contains("nc:EntityPerson/nc:PersonName/nc:PersonMaidenName", paths);
        Assert.Contains("nc:EntityPerson/nc:PersonName/nc:PersonFullName", paths);
        Assert.Contains("nc:EntityPerson/nc:PersonName/nc:PersonNameCommentText", paths);

        // Each dropped field must have a non-empty reason (audit trail invariant).
        Assert.All(person.NotSurfacedWsdlFields, f =>
            Assert.False(string.IsNullOrWhiteSpace(f.Reason), $"NotSurfacedWsdlField '{f.Path}' has empty Reason."));
    }

    [Fact]
    public void TFourA_StubAnnotations_PairEmptyListWithAuditNote()
    {
        // Stub form: empty NotSurfacedWsdlFields + AuditNote string. Verifies
        // the four composite variants beyond caseParticipant.person follow the
        // stub pattern (organization, caseAssignment.attorney, contact.default, address.default).
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var stubExpectations = new[]
        {
            ("caseParticipant", "organization"),
            ("caseAssignment", "attorney"),
            ("contact", "default"),
            ("address", "default"),
        };

        foreach (var (ct, variantKey) in stubExpectations)
        {
            var variant = schema.ClassTypes[ct].Variants[variantKey];
            Assert.NotNull(variant.NotSurfacedWsdlFields);
            Assert.Empty(variant.NotSurfacedWsdlFields!);
            Assert.False(string.IsNullOrWhiteSpace(variant.AuditNote),
                $"{ct}.{variantKey} has empty NotSurfacedWsdlFields without AuditNote — must document why surfaced set is baseline-only.");
        }
    }

    [Fact]
    public void TFourA_RenderHintDistribution_MatchesAuditTable()
    {
        // Per PRE_T4_SCHEMA_GROUNDING_AUDIT.md § 2.3 / T-4-A.3 expected distribution:
        // compositeCard ×5, scalar ×8, dropdown ×1, complexDeferred ×5.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var counts = schema.ClassTypes.Values
            .GroupBy(ct => ct.RenderHint)
            .ToDictionary(g => g.Key!, g => g.Count());

        Assert.Equal(5, counts.GetValueOrDefault("compositeCard"));
        Assert.Equal(8, counts.GetValueOrDefault("scalar"));
        Assert.Equal(1, counts.GetValueOrDefault("dropdown"));
        Assert.Equal(5, counts.GetValueOrDefault("complexDeferred"));
    }

    [Fact]
    public void TFourA_BooleanClassType_FieldLabelIsYes_NotValue()
    {
        // T-4 scalar swap: the boolean classType's field label was
        // changed from "Value" to "Yes" because the document-metadata's `name`
        // (meta.Name) is the question and the inline checkbox label is the
        // affirmative answer ("Yes"). Pinning the corrected label here so a
        // future schema change cannot silently revert this without a test fail.
        // Grounded in 2 baseline samples (CIV-SUB-018 Self-Rep, FAM-SUB-004
        // custody flag).
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        Assert.True(schema.ClassTypes.TryGetValue("boolean", out var booleanCt),
            "Expected schema to contain `boolean` classType.");
        Assert.True(booleanCt!.Variants.TryGetValue("default", out var defaultVariant),
            "Expected `boolean` to have a `default` variant.");
        Assert.Single(defaultVariant!.Fields);
        var field = defaultVariant.Fields[0];
        Assert.Equal("booleanValue", field.Name);
        Assert.Equal("checkbox", field.Type);
        Assert.Equal("Yes", field.Label);
    }

    // ───────────────────────────────────────────────────────────────────
    // T-4 contact composite audit. Pre-composite-swap audit
    // surfaced 3 schema source-name bugs that lived in the schema since
    // T-3a (~3+ weeks pre-existing). Live verification against Madera
    // staging /api/codelist endpoint:
    //   STATE         → returned [] (BUG: should be US_STATE — incumbent SF view always used US_STATE)
    //   COUNTRY       → returned 797 bytes (works but ADDRESS_COUNTRY returns 4814 bytes — canonical per JTI EFM)
    //   PHONE_TYPE    → returned [] (BUG: should be TELEPHONE_TYPE — TELEPHONE_TYPE returns 5 entries)
    //   ADDRESS_TYPE  → returned 675 bytes (correct, no change)
    // None of these bugs were caught earlier because no code path exercised
    // them — incumbent SF view used hardcoded `usStates` for state and
    // silently dropped country/addressType/telephoneType entirely. T-4
    // contact composite would have hit all 3 bugs on first integration.
    // The tests below pin the corrected source names so this drift cannot
    // recur silently.
    // ───────────────────────────────────────────────────────────────────

    [Fact]
    public void TFourA_ContactComposite_StateField_UsesUsStateCodelist_NotStateCodelist()
    {
        // STATE returned [] from Madera /api/codelist; US_STATE returned 50 entries.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var contactCt = schema.ClassTypes["contact"];
        var defaultVariant = contactCt.Variants["default"];
        var stateField = defaultVariant.Fields.Single(f => f.Name == "state");
        Assert.Equal("dropdown", stateField.Type);
        Assert.Equal("US_STATE", stateField.Source);
        Assert.True(stateField.Required, "`state` field should be required (V0 baseline grounding — every contact sample emits state).");
    }

    [Fact]
    public void TFourA_ContactComposite_CountryField_UsesAddressCountryCodelist_NotCountryCodelist()
    {
        // ADDRESS_COUNTRY is the canonical JTI name (per memory 8fc21aaf). Both
        // names work on Madera but ADDRESS_COUNTRY returns the comprehensive list
        // (4814 vs 797 bytes).
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var contactCt = schema.ClassTypes["contact"];
        var defaultVariant = contactCt.Variants["default"];
        var countryField = defaultVariant.Fields.Single(f => f.Name == "country");
        Assert.Equal("dropdown", countryField.Type);
        Assert.Equal("ADDRESS_COUNTRY", countryField.Source);
        Assert.Equal("US", countryField.Default);
        Assert.False(countryField.Required, "`country` field should be optional (defaults to US).");
    }

    [Fact]
    public void TFourA_ContactComposite_TelephoneTypeField_UsesTelephoneTypeCodelist_NotPhoneTypeCodelist()
    {
        // PHONE_TYPE returned [] from Madera; TELEPHONE_TYPE returned 5 entries.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var contactCt = schema.ClassTypes["contact"];
        var defaultVariant = contactCt.Variants["default"];
        var phoneTypeField = defaultVariant.Fields.Single(f => f.Name == "telephoneType");
        Assert.Equal("dropdown", phoneTypeField.Type);
        Assert.Equal("TELEPHONE_TYPE", phoneTypeField.Source);
    }

    [Fact]
    public void TFourA_ContactComposite_TenSchemaDeclaredFields_FullShape()
    {
        // Pins the 10-field shape of the contact composite. Incumbent SF view's
        // `buildContactFields` only renders 7 of these 10 (silently drops
        // country, addressType, telephoneType). Catalogued as C-2 territory
        // pre-existing bug. Future composite swap will fix this once form-submit
        // collection logic is refactored to handle the 3 currently-dropped fields.
        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var contactCt = schema.ClassTypes["contact"];
        Assert.Equal("compositeCard", contactCt.RenderHint);
        var defaultVariant = contactCt.Variants["default"];
        Assert.Equal(10, defaultVariant.Fields.Count);
        var byName = defaultVariant.Fields.ToDictionary(f => f.Name);

        // Required fields (4): address1, city, state, zip
        Assert.True(byName["address1"].Required);
        Assert.True(byName["city"].Required);
        Assert.True(byName["state"].Required);
        Assert.True(byName["zip"].Required);

        // Optional fields (6): address2, country, addressType, telephoneType, telephoneNumber, email
        Assert.False(byName["address2"].Required);
        Assert.False(byName["country"].Required);
        Assert.False(byName["addressType"].Required);
        Assert.False(byName["telephoneType"].Required);
        Assert.False(byName["telephoneNumber"].Required);
        Assert.False(byName["email"].Required);

        // maxLength constraints (incumbent has none of these):
        Assert.Equal(200, byName["address1"].MaxLength);
        Assert.Equal(200, byName["address2"].MaxLength);
        Assert.Equal(100, byName["city"].MaxLength);
        Assert.Equal(10, byName["zip"].MaxLength);
        Assert.Equal(20, byName["telephoneNumber"].MaxLength);
        Assert.Equal(100, byName["email"].MaxLength);

        // Field types
        Assert.Equal("text", byName["address1"].Type);
        Assert.Equal("text", byName["address2"].Type);
        Assert.Equal("text", byName["city"].Type);
        Assert.Equal("dropdown", byName["state"].Type);
        Assert.Equal("text", byName["zip"].Type);
        Assert.Equal("dropdown", byName["country"].Type);
        Assert.Equal("dropdown", byName["addressType"].Type);
        Assert.Equal("dropdown", byName["telephoneType"].Type);
        Assert.Equal("tel", byName["telephoneNumber"].Type);
        Assert.Equal("email", byName["email"].Type);
    }

    [Fact]
    public void TFourA_AllClassTypes_AllDropdownSources_AreLiveVerifiedNames()
    {
        // Defense-in-depth test: every dropdown field in EVERY classType / variant
        // must use a source name that we've live-verified against Madera (or
        // the 'dynamic' sentinel meaning "host page supplies the codelist name
        // at runtime"). This catches a future schema edit that introduces a new
        // dropdown with an unverified source name — which would silently fall
        // back to [] from Madera's codelist API and produce an empty dropdown.
        //
        // ORIGINALLY scoped to just the contact composite — but the address
        // composite had the SAME 2 source-name bugs (STATE/COUNTRY) and the
        // contact-only test missed them. Generalized 2026-05-17 to cover all
        // classTypes so any similar slip surfaces immediately.
        //
        // Live verification protocol when adding a new source name:
        //   1. Run: GET http://localhost:58086/CourtFiling/api/codelist?courtId=madera&codeListType={SOURCE}
        //   2. Confirm response is non-empty array
        //   3. Add the source name to `liveVerified` below + cite the verification date
        var liveVerified = new HashSet<string>(StringComparer.Ordinal)
        {
            // Verified 2026-05-17 against Madera staging /api/codelist endpoint:
            "US_STATE",         // 50 entries (was 'STATE' which returned [])
            "ADDRESS_COUNTRY",  // 4814 bytes — canonical (was 'COUNTRY' which returned 797 bytes)
            "ADDRESS_TYPE",     // 675 bytes — Mailing/Work/Home/etc.
            "TELEPHONE_TYPE",   // 5 entries (was 'PHONE_TYPE' which returned [])
            "PARTY_TYPE",       // 357826 bytes — large list of party-role codes (Administrator, Plaintiff, etc.)

            // Sentinel: source 'dynamic' means the host page supplies the codelist
            // name at runtime via spec.dynamicSource (e.g., codeList classType
            // delegates to meta.CodeList from document metadata).
            "dynamic"
        };

        var schema = JtiFieldSchemaProvider.GetClassTypeSchema();
        var failures = new List<string>();
        foreach (var (classTypeName, classType) in schema.ClassTypes)
        {
            foreach (var (variantName, variant) in classType.Variants)
            {
                if (variant.Fields == null) continue;
                foreach (var field in variant.Fields.Where(f => f.Type == "dropdown"))
                {
                    if (string.IsNullOrEmpty(field.Source))
                    {
                        failures.Add($"{classTypeName}.{variantName}.{field.Name}: missing `source`");
                        continue;
                    }
                    if (!liveVerified.Contains(field.Source))
                    {
                        failures.Add($"{classTypeName}.{variantName}.{field.Name}: source=`{field.Source}` NOT in live-verified set");
                    }
                }
            }
        }
        Assert.True(failures.Count == 0,
            $"The following dropdown fields use sources not in the live-verified set:" +
            Environment.NewLine + string.Join(Environment.NewLine, failures) +
            Environment.NewLine + Environment.NewLine +
            $"Live-verified set: [{string.Join(", ", liveVerified)}]" +
            Environment.NewLine +
            "To resolve: GET http://localhost:58086/CourtFiling/api/codelist?courtId=madera&codeListType={SOURCE}, confirm non-empty, add to set.");
    }
}
