using EFiling.Providers.JTI.Config;

namespace EFiling.Tests;

/// <summary>
/// Step #45 — T-8 stub completion re-survey.
///
/// <para>
/// <b>Audit summary:</b> Re-surveyed all JTI sample XMLs in
/// <c>docs/fileing files/</c>, the WSDL-generated <c>Reference.cs</c> in
/// <c>EFiling.WsdlGenerated/</c>, and live Madera captures for evidence of
/// each schema-declared classType that's currently marked
/// <c>awaitingEvidence: true</c>. Found ZERO new evidence since Step #15
/// (judgment promotion, 2026-05-19). All 9 remaining stubs (crsReceiptNumber,
/// number, email, action, address, document, scheduledEvent,
/// caseSpecialStatus, relatedCase) remain evidence-blocked.
/// </para>
///
/// <para>
/// <b>Notable false positives during survey:</b>
/// </para>
/// <list type="bullet">
///   <item>The LASC COVID-19 sample uses <c>&lt;ns6:CaseSpecialStatus&gt;</c>
///     at CASE-extension level (not a metadata item), so it does NOT count
///     as evidence for the <c>caseSpecialStatus</c> classType which expects
///     a metadata-item <c>&lt;caseSpecialStatusValue&gt;</c> wrapper.
///     Different wire shapes despite the similar name.</item>
///   <item>Wrapper-element substring matches inside <c>xmlns:</c> namespace
///     declarations (e.g., <c>NumberValue</c> appearing inside a
///     <c>targetNamespace</c> URI) are not evidence of the classType being
///     used in any sample.</item>
/// </list>
///
/// <para>
/// <b>Strict source-fidelity verdict:</b> Cannot implement any of the 9 on
/// faith. Each remains correctly fail-closed via the schema-aware default
/// arm in <see cref="EFiling.Providers.JTI.Builders.ReviewFilingXmlBuilder"/>
/// (existing <c>T8StubSweep</c> Theory locks the throw behavior).
/// </para>
///
/// <para>
/// <b>Forcing function:</b> The per-stub Theory below asserts each of the 9
/// stubs still carries <c>awaitingEvidence: true</c> AND
/// <c>baselineSampleCount: 0</c> in <c>JtiClassTypeSchema.json</c>. If a
/// future audit promotes any of them (evidence surfaces, builder arm
/// implemented, schema flag flipped), the corresponding test row fails —
/// forcing the engineer to also remove the row from
/// <see cref="ReviewFilingXmlBuilderTests"/> <c>T8StubSweep</c> InlineData
/// and update the Step #45 survey results in PROGRESS.md.
/// </para>
///
/// <para>
/// <b>Why no cardinality lock:</b> The schema has 12 entries with
/// <c>awaitingEvidence:true</c> total — the 9 stubs surveyed here PLUS
/// <c>text</c>, <c>currency</c>, <c>attorney</c> which all have builder
/// arms but no captured baseline sample (their builder shape is a
/// WSDL/HTML-doc hypothesis awaiting wire verification). A naive
/// <c>count==9</c> test would be wrong; per-stub Theory rows capture the
/// "stub" subset precisely.
/// </para>
/// </summary>
public class Step45_T8StubSurveyTests
{
    /// <summary>
    /// Per-stub evidence-pinning Theory. Each of the 9 entries below was
    /// independently verified to have ZERO sample / WSDL / live-capture
    /// evidence during the Step #45 survey.
    /// </summary>
    [Theory]
    [InlineData("number",            "V3", "First sample with classType=number.")]
    [InlineData("email",             "V3", "First sample with classType=email.")]
    [InlineData("action",            "V3", "First sample OR Madera/LASC GetPolicy declaring classType=action.")]
    [InlineData("address",           "V3", "First sample confirming sta1:StructuredAddress children.")]
    [InlineData("document",          "V3", "First sample OR GetPolicy declaring classType=document.")]
    [InlineData("scheduledEvent",    "V3", "First sample OR GetPolicy declaring classType=scheduledEvent.")]
    [InlineData("caseSpecialStatus", "V3", "First sample with metadata-item classType=caseSpecialStatus (NOT the case-level <CaseSpecialStatus> UDCOV19 wrapper).")]
    [InlineData("relatedCase",       "V3", "First sample with classType=relatedCase.")]
    // Step #46 — `crsReceiptNumber` row REMOVED from this Theory because
    // it was promoted via JTI HTML Layer A evidence (Document Metadata page Class
    // Types section enumerates it as "String. The calendar reservation number
    // generated by the CRS system."). Builder + parser arms landed alongside.
    // The 8 remaining rows are Tier-3 stubs — NOT in JTI's canonical "Class Types"
    // list at all, blocked structurally rather than awaiting-sample-blocked. See
    // Step45_T8StubSurvey_Tier3Stubs_AreFlaggedJtiCanonicalListedFalse below for
    // the matching Tier-3 invariant.
    public void Step45_T8StubSurvey_StillAwaitingEvidence_2026_05_21(
        string classType, string expectedEvidenceLevel, string promotionCriteriaHint)
    {
        var schemaDef = JtiFieldSchemaProvider.GetClassTypeV2(classType);

        Assert.NotNull(schemaDef);
        Assert.True(schemaDef.AwaitingEvidence,
            $"Step #45 surveyed classType '{classType}' and found ZERO " +
            $"evidence. If you have since implemented a builder arm for this classType " +
            $"(sample + tests landed), flip awaitingEvidence to false in " +
            $"JtiClassTypeSchema.json, remove this Theory row, and update the Step #45 " +
            $"survey results in PROGRESS.md. Promotion criteria: {promotionCriteriaHint}");

        Assert.Equal(expectedEvidenceLevel, schemaDef.Evidence?.Level);
        Assert.Equal(0, schemaDef.Evidence?.BaselineSampleCount);
    }

    /// <summary>
    /// Step #46 follow-on lock. The deep-probe of JTI HTML docs in
    /// Path 2 of Step #46 surfaced that the JTI Document Metadata page's
    /// <c>&lt;h3&gt;Class Types&lt;/h3&gt;</c> section enumerates exactly 10
    /// canonical classTypes. The 8 stubs that remain after promoting
    /// <c>crsReceiptNumber</c> are NOT in this canonical list — they're
    /// structurally out-of-scope (WSDL wrappers JTI doesn't expose as
    /// filer-controllable classTypes). This Theory pins the schema flag
    /// <c>jtiCanonicalListed: false</c> on each Tier-3 entry so any future
    /// re-classification fires the corresponding row.
    /// </summary>
    [Theory]
    [InlineData("number")]
    [InlineData("email")]
    [InlineData("action")]
    [InlineData("address")]
    [InlineData("document")]
    [InlineData("scheduledEvent")]
    [InlineData("caseSpecialStatus")]
    [InlineData("relatedCase")]
    public void Step45_T8StubSurvey_Tier3Stubs_AreFlaggedJtiCanonicalListedFalse(string classType)
    {
        var schemaDef = JtiFieldSchemaProvider.GetClassTypeV2(classType);

        Assert.NotNull(schemaDef);
        Assert.Equal(false, schemaDef.JtiCanonicalListed);
    }

    /// <summary>
    /// Companion: the 10 JTI canonical-listed classTypes (per the Document
    /// Metadata HTML doc Class Types section) should NOT carry an explicit
    /// <c>jtiCanonicalListed: false</c> flag (they're either null/unset — the
    /// implicit default for canonical — or could be marked true if a future
    /// audit adds explicit positive marking).
    /// </summary>
    [Theory]
    [InlineData("attorney")]
    [InlineData("boolean")]
    [InlineData("caseparticipant")]
    [InlineData("contact")]
    [InlineData("crsReceiptNumber")]
    [InlineData("currency")]
    [InlineData("date")]
    [InlineData("judgment")]
    [InlineData("text")]
    [InlineData("codelist")]
    public void Step46_JtiCanonicalListedClassTypes_AreNotFlaggedFalse(string classType)
    {
        var schemaDef = JtiFieldSchemaProvider.GetClassTypeV2(classType);

        Assert.NotNull(schemaDef);
        Assert.NotEqual(false, schemaDef.JtiCanonicalListed);
    }

    /// <summary>
    /// Sanity lock: <c>judgment</c> was promoted to evidence-backed in
    /// Step #15 via the LASC Writ of Return sample. Its
    /// top-level <c>awaitingEvidence</c> must remain <c>false</c>. If
    /// someone accidentally re-flags it true, this test fails to catch the
    /// regression.
    ///
    /// (Note the nested <c>valueRestrictions.newData.awaitingEvidence</c>
    /// remains <c>true</c> — that's correct, since no new-data baseline
    /// has surfaced — but the top-level flag tracks the classType-as-a-whole
    /// promotion status.)
    /// </summary>
    [Fact]
    public void Step45_T8StubSurvey_JudgmentPromotion_Stays_AwaitingEvidenceFalse()
    {
        var judgment = JtiFieldSchemaProvider.GetClassTypeV2("judgment");

        Assert.NotNull(judgment);
        Assert.False(judgment.AwaitingEvidence,
            "classType 'judgment' was promoted in Step #15 and should remain " +
            "awaitingEvidence=false at the TOP level (the nested newData.awaitingEvidence " +
            "may still be true — that tracks a separate sub-promotion). If this assertion " +
            "fires, someone reverted the promotion. See docs/STEP15_JUDGMENT_AUDIT.md for " +
            "context.");
    }
}
