namespace EFiling.Core.Models;

/// <summary>
/// A document included in a filing submission.
/// </summary>
public class FilingDocument
{
    /// <summary>Local reference ID (e.g., "doc0", "doc1").</summary>
    public string ReferenceId { get; set; } = string.Empty;

    /// <summary>Document type code from court policy (e.g., "COM040", "RES010").</summary>
    public string DocumentCode { get; set; } = string.Empty;

    /// <summary>Sequence number (0-based).</summary>
    public int SequenceNumber { get; set; }

    /// <summary>URL where the EFM can download the document. Must have file extension, no spaces.</summary>
    public string BinaryLocationUri { get; set; } = string.Empty;

    /// <summary>MIME type (e.g., "application/pdf").</summary>
    public string MimeType { get; set; } = "application/pdf";

    /// <summary>Optional name extension appended to document name.</summary>
    public string? NameExtension { get; set; }

    /// <summary>Optional EFSP file control identifier.</summary>
    public string? FileControlId { get; set; }

    /// <summary>Complaint/sub-case ID this document belongs to (subsequent filing).</summary>
    public string? ComplaintRef { get; set; }

    /// <summary>IdentificationSourceText for DocumentIdentification (e.g., party role code like "PLA").</summary>
    public string? IdentificationSourceText { get; set; }

    /// <summary>Document filing metadata items (subsequent filing).</summary>
    public List<FilingMetadataValue> MetadataValues { get; set; } = new();
}

/// <summary>
/// A metadata value for a document in a subsequent filing.
/// </summary>
public class FilingMetadataValue
{
    /// <summary>Metadata code (e.g., "FILED_BY", "AS_TO", "PAYMENT_OPTION").</summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>Class type (e.g., "caseParticipant", "codeList", "boolean").</summary>
    public string ClassType { get; set; } = string.Empty;

    /// <summary>Sub-type (e.g., "filed-by", "refers-to").</summary>
    public string? SubType { get; set; }

    /// <summary>Value restriction ("new-data" or "existing-data").</summary>
    public string? ValueRestriction { get; set; }

    // ─── Value Fields (set the one matching ClassType) ──────────────

    /// <summary>Text value (classType: text).</summary>
    public string? TextValue { get; set; }

    /// <summary>Boolean value (classType: boolean).</summary>
    public bool? BooleanValue { get; set; }

    /// <summary>Code value (classType: codeList).</summary>
    public string? CodeValue { get; set; }

    /// <summary>Currency value (classType: currency).</summary>
    public decimal? CurrencyValue { get; set; }

    /// <summary>Date value (classType: date).</summary>
    public DateTime? DateValue { get; set; }

    /// <summary>
    /// CRS receipt number value (classType: crsReceiptNumber). Step #46
    ///: promoted from T-8 stub to implemented arm based on
    /// JTI HTML doc "Document Metadata / Class Types" enumeration which
    /// defines crsReceiptNumber as *"String. The calendar reservation
    /// number generated by the CRS system."* WSDL wire shape is the scalar
    /// <c>&lt;crsReceiptNumberValue&gt;{string}&lt;/crsReceiptNumberValue&gt;</c>
    /// wrapper (FilingReview/Reference.cs:11474). Same evidence tier as
    /// <c>text</c> / <c>currency</c> (JTI HTML Layer A; no baseline sample).
    /// </summary>
    public string? CrsReceiptNumberValue { get; set; }

    /// <summary>
    /// Existing party/attorney reference IDs (classType: caseParticipant/attorney with existing-data).
    /// </summary>
    public List<string> IdReferences { get; set; } = new();

    /// <summary>
    /// Per-id existing-data references with per-id tags. Canonical wire-shape field for
    /// caseParticipant / caseAssignment / attorney classTypes in existing-data mode. Mirrors
    /// the WSDL <c>TaggedReferenceType[]</c> shape exactly: each reference carries its own
    /// optional <c>AdditionalInfoTags</c>.
    /// <para>
    /// Step #14 audit — closes silent-drop #10 (per-id tag cross-contamination in
    /// <c>ReviewFilingXmlBuilder</c> caseparticipant / attorney / caseassignment branches,
    /// pre-fix lines 883-894 / 966-975 / 997-1006). When this collection is non-empty the
    /// builder uses it AND ignores the legacy <see cref="IdReferences"/> +
    /// <see cref="AdditionalInfoTags"/> fields. When empty the builder falls back to legacy
    /// fields (back-compat for single-id callers; multi-id callers with tags MUST migrate
    /// to <c>TaggedReferences</c> to avoid the cross-contamination bug).
    /// </para>
    /// </summary>
    public List<TaggedReference> TaggedReferences { get; set; } = new();

    /// <summary>
    /// New party data (classType: caseParticipant with new-data). Convenience single-valued
    /// field; treated as the first element of <see cref="NewPartyValues"/>. Writes and reads
    /// through this property are transparently proxied to/from the list so existing callers
    /// that set <c>NewPartyValue = new FilingParty {...}</c> keep working (Audit H-1 fix,
    /// 2026-04-22).
    /// </summary>
    public FilingParty? NewPartyValue
    {
        get => NewPartyValues.Count > 0 ? NewPartyValues[0] : null;
        set
        {
            NewPartyValues.Clear();
            if (value != null) NewPartyValues.Add(value);
        }
    }

    /// <summary>
    /// New party data collection (classType: caseParticipant with new-data). Baseline wires
    /// can emit MULTIPLE <c>&lt;caseParticipantValue&gt;</c> elements inside a single
    /// <c>&lt;documentFilingMetaDataItem&gt;</c> — e.g., CIV-SUB-001 NEW_RESPONDING_PARTY
    /// has two defendants (Ron Wilson + Jacob Tillis) grouped under one metadata item.
    /// Each element becomes a distinct <see cref="FilingParty"/> with full name / role /
    /// contact fidelity. Audit H-1 fix — pre-fix the model only held a single
    /// party per item and the builder silently dropped names / role / eService.
    /// </summary>
    public List<FilingParty> NewPartyValues { get; set; } = new();

    /// <summary>New attorney data (classType: attorney with new-data).</summary>
    public AttorneyInfo? NewAttorneyValue { get; set; }

    /// <summary>Contact value (classType: contact).</summary>
    public ContactValueData? ContactValue { get; set; }

    /// <summary>Case assignment data (classType: caseAssignment with new-data).</summary>
    public CaseAssignmentData? CaseAssignmentValue { get; set; }

    /// <summary>Additional info tags on idReferences (e.g., E_SERVICE, FEE_EXEMPTION).</summary>
    public List<AdditionalInfoTag> AdditionalInfoTags { get; set; } = new();

    /// <summary>
    /// Existing-judgment reference IDs (classType: <c>judgment</c> with existing-data).
    /// <para>
    /// Wire shape per LASC Writ of Return sample + WSDL <c>CourtEventJudgmentType.judgmentId</c>:
    /// </para>
    /// <code>
    /// &lt;ns9:judgments&gt;
    ///   &lt;ns10:judgmentId&gt;{id}&lt;/ns10:judgmentId&gt;
    /// &lt;/ns9:judgments&gt;
    /// </code>
    /// <para>
    /// Step #15 (Path C, see <c>STEP15_JUDGMENT_AUDIT.md</c>) — judgment is the only
    /// classType where the wrapper element (<c>&lt;judgments&gt;</c>, plural, in
    /// DocumentFilingMetaData namespace) and content element
    /// (<c>&lt;judgmentId&gt;</c>, in CourtEventJudgment namespace) live in different
    /// namespaces. Distinct from the universal <c>&lt;idReferences&gt;</c> /
    /// <c>&lt;TaggedReferences&gt;</c> pattern used by caseParticipant + caseAssignment +
    /// attorney.
    /// </para>
    /// <para>
    /// New-data path (filing a brand-new judgment with full <c>JudgmentAwardType</c>
    /// content) is <b>not implemented</b> — schema marks <c>newData.awaitingEvidence</c>;
    /// builder throws <see cref="System.NotImplementedException"/> when
    /// <see cref="ValueRestriction"/> != "existing-data" on a judgment metadata value.
    /// </para>
    /// </summary>
    public List<string> JudgmentIds { get; set; } = new();

    /// <summary>
    /// Step #16 — atomic single-id replacement helper. Mutates BOTH the
    /// canonical wire-source (<see cref="TaggedReferences"/>) AND the legacy
    /// back-compat projections (<see cref="IdReferences"/> + <see cref="AdditionalInfoTags"/>)
    /// in one call so they cannot drift.
    ///
    /// <para>
    /// <b>Why this exists:</b> Step #14 (2026-05-19→05-21) ratcheted the wire-builder
    /// ABI: <c>ReviewFilingXmlBuilder</c> now emits from <see cref="TaggedReferences"/>
    /// (canonical, mirrors WSDL <c>TaggedReferenceType[]</c>); <see cref="IdReferences"/> +
    /// <see cref="AdditionalInfoTags"/> are kept populated as back-compat projections for
    /// READERS (test asserts, log formatters). Code that mutates only the legacy fields
    /// (Tier B fixture overrides authored pre-Step-#14, programmatic submission tweaks)
    /// silently lies on the wire because <see cref="TaggedReferences"/> retains the
    /// stale parsed-from-baseline values that the builder emits instead. Step #16
    /// audit (<c>STEP16_TIERB_FIXTURE_DRIFT_AUDIT.md</c>) discovered this on the
    /// 2026-05-20 FAM-SUB-004 Tier B resubmit (silent-drop scoreboard #15 in
    /// <c>SF_LEGACY_INVENTORY.md</c>). This helper closes the gap by making
    /// "replace this metadata value's ref with this single id (and optionally tags)"
    /// a single atomic operation that hits both shapes.
    /// </para>
    ///
    /// <para>
    /// <b>Use this from:</b> any code that needs to <i>replace</i> the entire
    /// id-references list of a metadata value with a single id — the dominant
    /// substitute-attorney / substitute-filer pattern in <c>MaderaLiveFixtures</c>.
    /// For multi-id replacement, call this helper repeatedly OR clear and use
    /// <see cref="TaggedReferences"/> directly with explicit legacy-field sync.
    /// </para>
    /// </summary>
    /// <param name="id">The single existing-entity primary id to replace all refs with.
    /// Must be non-null and non-empty.</param>
    /// <param name="tags">Optional tags to attach to this id (e.g., E_SERVICE,
    /// FEE_EXEMPTION). Pass <c>null</c> or an empty enumerable for no tags. Tags are
    /// materialized into both <see cref="TaggedReferences"/>[0].Tags AND the flat
    /// <see cref="AdditionalInfoTags"/> back-compat list.</param>
    /// <exception cref="ArgumentException">Thrown when <paramref name="id"/> is null or empty.</exception>
    public void ReplaceWithSingleId(string id, IEnumerable<AdditionalInfoTag>? tags = null)
    {
        if (string.IsNullOrEmpty(id))
            throw new ArgumentException("Id must be non-empty.", nameof(id));

        var tagList = tags?.ToList() ?? new List<AdditionalInfoTag>();

        // Canonical wire-source — Step #14 builder reads from here.
        TaggedReferences.Clear();
        TaggedReferences.Add(new TaggedReference { Id = id, Tags = tagList });

        // Legacy back-compat projections — kept in sync so readers (test asserts,
        // log formatters) see the same data the builder emits.
        IdReferences.Clear();
        IdReferences.Add(id);

        AdditionalInfoTags.Clear();
        AdditionalInfoTags.AddRange(tagList);
    }
}

/// <summary>
/// A tag/value pair for additionalInfoTags on metadata idReferences.
/// </summary>
public class AdditionalInfoTag
{
    public string TagType { get; set; } = string.Empty;
    public string TagValue { get; set; } = string.Empty;
}

/// <summary>
/// A reference to an existing entity (party or attorney) on the wire, paired with its OWN
/// optional <see cref="AdditionalInfoTag"/> list. Mirrors the WSDL <c>TaggedReferenceType</c>
/// (FilingReview <c>Reference.cs:22240-22274</c>) and the corresponding NIEM/JTI schema
/// <c>JtiClassTypeSchema.json</c> <c>valueRestrictions.existingData.wire</c> entry.
/// <para>
/// Step #14 — replaces the prior parallel <see cref="FilingMetadataValue.IdReferences"/> +
/// <see cref="FilingMetadataValue.AdditionalInfoTags"/> design which cross-contaminated tags
/// across all ids when both lists were populated.
/// </para>
/// </summary>
public class TaggedReference
{
    /// <summary>Existing-entity primary id (e.g., party primary id, attorney id).</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Optional per-id tags (FEE_EXEMPTION, E_SERVICE, EFSP_EMAIL, etc.).</summary>
    public List<AdditionalInfoTag> Tags { get; set; } = new();
}

/// <summary>
/// New attorney data for caseAssignment classType with new-data valueRestriction.
/// </summary>
public class CaseAssignmentData
{
    public string? FirstName { get; set; }
    public string? MiddleName { get; set; }
    public string? LastName { get; set; }

    /// <summary>Person name suffix (Jr., Sr., III, etc.).</summary>
    /// <remarks>
    /// Pre-2026-05-17 silent-drop chain: JS captured suffix via .att-suffix → DTO held it on
    /// MetadataValueDto.Suffix → mapper ignored it → wire model + builder had no hole to put
    /// it in. Closed end-to-end now, schema-aligned with caseAssignment.attorney + main party
    /// new-data which already supported it.
    /// </remarks>
    public string? NameSuffix { get; set; }

    public string? BarNumber { get; set; }
    public string? FirmName { get; set; }
    public string AssignmentRole { get; set; } = "ATT";
    public ContactInfo? Contact { get; set; }
    public bool EService { get; set; }
}

/// <summary>
/// Flat contact value for DocumentFilingMetaData (classType: contact).
/// Matches JTI ContactValue schema.
/// </summary>
public class ContactValueData
{
    public string? Address1 { get; set; }
    public string? Address2 { get; set; }
    public string? City { get; set; }
    public string? Zip { get; set; }
    public string? State { get; set; }
    public string? Country { get; set; }
    public string? PhoneNumber { get; set; }
    public string? PhoneType { get; set; }
    public string? Email { get; set; }
    public string? AddressType { get; set; }
}
